### ISSUE TITLE
second layer of nested pure components does not receive all properties

### ISSUE THREAD

**Issue by qlbit-com** [kachurun/riot-pure-props#1]
I'm playing with nesting pure components. 
The layout is as follows:

```
  <ql-split row='true' sizes={[25,50,25]}>
    <h2 slot='item1'> aaa </h2>
    <ql-split row='true' sizes={[25,50,25]} slot='foo'>
      <h2 slot='item4'> bbb </h2>
      <h2 slot='item3'> ccc </h2>
    </ql-split>
  </ql-split>
```

code for ql-split looks as follows:
```
<ql-split>
  <script>
    import { pure } from 'riot'
    import getProps from 'riot-pure-props';

    export default pure( ( { attributes, slots, props } )=> ( {
      mount( el, context ) {
        this.props = getProps( el, context, attributes, props )
        ....
   
```

at first level props are populated -- both 'row' and 'sizes', 
on the second level I only can sees 'sizes', though 'row' is missing.

Ironically, property is visible on the second layer when that property is dynamic like row={} -- it is being resolved as row=''
```
  <ql-split row={} sizes={[25,50,25]}>
    <h2 slot='item1'> aaa </h2>
    <ql-split row={} sizes={[25,50,25]} slot='foo'>
      <h2 slot='item4'> bbb </h2>
      <h2 slot='item3'> ccc </h2>
    </ql-split>
  </ql-split>
```
So workaround is available, though plain attributes are not populated into nested layer as properties. 
My best bet is RiotJS core issue.
Please advise.

Isolated test:
https://plnkr.co/edit/6M9vy1KyjfXWlyue

Best,
~Dmitriy

**Comment by kachurun** [comment]
Привет Дмитрий, я полагаю ты понимаешь по русски, так что не буду заморачиваться.

Я отписал в оригинальном ишью:
https://github.com/riot/riot/issues/2918#issuecomment-857542563

Проблема в неправильно переданном в слот контексте, из-за чего у тебя пропсы берутся из корневого pure компонента. Это должно создавать вагон других багов.

Я кстати не тестировал никогда создание слотов в pure компонентах на лету, не было такой нужды, поэтому возможно там есть другие проблемы, но на первый взгляд все работает корректно (см. пример в планкере по ссылке выше).

Таск закрываю т.к к этой репе он отношения не имеет.
